name: Bitso Workflow
on:
  pull_request:
    branches:
      - master
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
jobs:
  stageReadiness:
    runs-on: ubuntu-latest
    name: Check for Stage Readiness
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'stageReady') }}
    steps:
      - name: skip or fail if no tag is found 
        run: |
          echo "Send this to stage first."
          exit 1
  buildStage:
    runs-on: ubuntu-latest
    name: Send to Stage
    if: contains(github.event.pull_request.labels.*.name, 'stageReady')
    steps:
      - name: init runner to build image 
        run: |
          curl https://api.github.com
          echo "Sent runner to build image."
  signOff:
    runs-on: ubuntu-latest
    name: Check for Sign-off
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'signedOff') }}
    steps:
      - name: fail check
        run: |
          echo "Must be signed off before merging"
          exit 1
